"""Frozen initial TASK-003 physical schema; never import mutable model metadata here."""

import sqlalchemy as sa
from alembic import context, op

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None

# Parent-before-child order is fixed with this revision, not taken from live models.
TABLES = (
    "deletion_confirmations",
    "tags",
    "topics",
    "learning_resources",
    "active_review_plans",
    "learning_progress",
    "notes",
    "original_files",
    "resource_tags",
    "review_records",
    "study_records",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deletion_confirmations",
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("resource_version", sa.Integer(), nullable=False),
        sa.Column("token_digest", sa.String(length=64), nullable=False),
        sa.Column("impact_manifest", sa.JSON(none_as_null=True), nullable=False),
        sa.Column("impact_revision", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("used_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "expires_at > created_at", name=op.f("ck_deletion_confirmations_expiry_after_creation")
        ),
        sa.CheckConstraint(
            "length(impact_revision) BETWEEN 64 AND 64",
            name=op.f("ck_deletion_confirmations_impact_revision_length"),
        ),
        sa.CheckConstraint(
            "length(token_digest) BETWEEN 64 AND 64",
            name=op.f("ck_deletion_confirmations_token_digest_length"),
        ),
        sa.CheckConstraint(
            "resource_version >= 1",
            name=op.f("ck_deletion_confirmations_resource_version_positive"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deletion_confirmations")),
        sa.UniqueConstraint("token_digest", name=op.f("uq_deletion_confirmations_token_digest")),
        info={"owner": "resources"},
    )
    op.create_index(
        op.f("ix_deletion_confirmations_expires_at"),
        "deletion_confirmations",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_deletion_confirmations_resource_id"),
        "deletion_confirmations",
        ["resource_id"],
        unique=False,
    )
    op.create_table(
        "tags",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("normalized_name", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("length(name) BETWEEN 1 AND 50", name=op.f("ck_tags_name_length")),
        sa.CheckConstraint(
            "length(normalized_name) >= 1", name=op.f("ck_tags_normalized_name_nonempty")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_tags_positive_version")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tags")),
        sa.UniqueConstraint("normalized_name", name=op.f("uq_tags_normalized_name")),
        info={"owner": "taxonomy"},
    )
    op.create_table(
        "topics",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("normalized_name", sa.Text(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "length(description) BETWEEN 0 AND 500", name=op.f("ck_topics_description_length")
        ),
        sa.CheckConstraint("length(name) BETWEEN 1 AND 80", name=op.f("ck_topics_name_length")),
        sa.CheckConstraint(
            "length(normalized_name) >= 1", name=op.f("ck_topics_normalized_name_nonempty")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_topics_positive_version")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_topics")),
        sa.UniqueConstraint("normalized_name", name=op.f("uq_topics_normalized_name")),
        info={"owner": "taxonomy"},
    )
    op.create_table(
        "learning_resources",
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("source_type", sa.String(length=5), nullable=False),
        sa.Column("source_url", sa.String(length=2048), nullable=True),
        sa.Column("pasted_content", sa.Text(), nullable=True),
        sa.Column("source_name", sa.String(length=120), nullable=True),
        sa.Column("save_reason", sa.String(length=1000), nullable=True),
        sa.Column("topic_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "(source_type = 'WEB' AND source_url IS NOT NULL AND pasted_content IS NULL) OR "
            "(source_type = 'PASTE' AND pasted_content IS NOT NULL AND source_url IS NULL) OR "
            "(source_type = 'FILE' AND source_url IS NULL AND pasted_content IS NULL)",
            name=op.f("ck_learning_resources_exclusive_source"),
        ),
        sa.CheckConstraint(
            "source_type IN ('WEB', 'FILE', 'PASTE')",
            name=op.f("ck_learning_resources_source_type"),
        ),
        sa.CheckConstraint(
            "length(pasted_content) BETWEEN 1 AND 1000000",
            name=op.f("ck_learning_resources_pasted_content_length"),
        ),
        sa.CheckConstraint(
            "length(save_reason) BETWEEN 0 AND 1000",
            name=op.f("ck_learning_resources_save_reason_length"),
        ),
        sa.CheckConstraint(
            "length(source_name) BETWEEN 0 AND 120",
            name=op.f("ck_learning_resources_source_name_length"),
        ),
        sa.CheckConstraint(
            "length(source_url) BETWEEN 1 AND 2048",
            name=op.f("ck_learning_resources_source_url_length"),
        ),
        sa.CheckConstraint(
            "length(title) BETWEEN 1 AND 200", name=op.f("ck_learning_resources_title_length")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_learning_resources_positive_version")),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
            name=op.f("fk_learning_resources_topic_id_topics"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learning_resources")),
        info={"owner": "resources"},
    )
    op.create_index(
        "ix_learning_resources_created_id", "learning_resources", ["created_at", "id"], unique=False
    )
    op.create_index(
        op.f("ix_learning_resources_topic_id"), "learning_resources", ["topic_id"], unique=False
    )
    op.create_table(
        "active_review_plans",
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=9), server_default="SCHEDULED", nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "(status = 'SCHEDULED' AND due_date IS NOT NULL) OR (status = 'PAUSED' AND due_date "
            "IS NULL)",
            name=op.f("ck_active_review_plans_scheduled_date"),
        ),
        sa.CheckConstraint(
            "status IN ('SCHEDULED', 'PAUSED')", name=op.f("ck_active_review_plans_status")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_active_review_plans_positive_version")),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["learning_resources.id"],
            name=op.f("fk_active_review_plans_resource_id_learning_resources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("resource_id", name=op.f("pk_active_review_plans")),
        info={"owner": "reviews"},
    )
    op.create_index(
        "ix_active_review_plans_status_due",
        "active_review_plans",
        ["status", "due_date", "resource_id"],
        unique=False,
    )
    op.create_table(
        "learning_progress",
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=11), server_default="UNREAD", nullable=False),
        sa.Column("progress_percent", sa.Integer(), server_default="0", nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("archived_from_status", sa.String(length=11), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "(status = 'ARCHIVED' AND archived_from_status IS NOT NULL AND archived_from_status "
            "<> 'ARCHIVED') OR (status <> 'ARCHIVED' AND archived_from_status IS NULL)",
            name=op.f("ck_learning_progress_archive_memory"),
        ),
        sa.CheckConstraint(
            "archived_from_status IN ('UNREAD', 'IN_PROGRESS', 'COMPLETED', 'REVIEW_DUE')",
            name=op.f("ck_learning_progress_archived_from_status"),
        ),
        sa.CheckConstraint(
            "status <> 'COMPLETED' OR completed_at IS NOT NULL",
            name=op.f("ck_learning_progress_completed_time"),
        ),
        sa.CheckConstraint(
            "status <> 'UNREAD' OR progress_percent = 0",
            name=op.f("ck_learning_progress_unread_progress"),
        ),
        sa.CheckConstraint(
            "status IN ('UNREAD', 'IN_PROGRESS', 'COMPLETED', 'REVIEW_DUE', 'ARCHIVED')",
            name=op.f("ck_learning_progress_status"),
        ),
        sa.CheckConstraint(
            "progress_percent BETWEEN 0 AND 100", name=op.f("ck_learning_progress_progress_bounds")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_learning_progress_positive_version")),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["learning_resources.id"],
            name=op.f("fk_learning_progress_resource_id_learning_resources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("resource_id", name=op.f("pk_learning_progress")),
        info={"owner": "learning"},
    )
    op.create_index(
        op.f("ix_learning_progress_status"), "learning_progress", ["status"], unique=False
    )
    op.create_table(
        "notes",
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "length(content) BETWEEN 1 AND 50000", name=op.f("ck_notes_content_length")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_notes_positive_version")),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["learning_resources.id"],
            name=op.f("fk_notes_resource_id_learning_resources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notes")),
        info={"owner": "notes"},
    )
    op.create_index(op.f("ix_notes_resource_id"), "notes", ["resource_id"], unique=False)
    op.create_table(
        "original_files",
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column("staging_key", sa.Text(), nullable=True),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("media_type", sa.String(length=71), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=7), server_default="PENDING", nullable=False),
        sa.Column("failure_code", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "(status = 'FAILED' AND failure_code IS NOT NULL AND length(failure_code) > 0) OR "
            "(status <> 'FAILED' AND failure_code IS NULL)",
            name=op.f("ck_original_files_failure_state"),
        ),
        sa.CheckConstraint(
            "media_type IN ('application/pdf', 'application/msword', "
            "'application/vnd.openxmlformats-officedocument.wordprocessingml.document', "
            "'text/markdown', 'text/plain')",
            name=op.f("ck_original_files_media_type"),
        ),
        sa.CheckConstraint(
            "status <> 'READY' OR staging_key IS NULL",
            name=op.f("ck_original_files_ready_staging_cleared"),
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'READY', 'FAILED')", name=op.f("ck_original_files_status")
        ),
        sa.CheckConstraint(
            "length(original_name) BETWEEN 1 AND 255",
            name=op.f("ck_original_files_original_name_length"),
        ),
        sa.CheckConstraint(
            "length(sha256) BETWEEN 64 AND 64", name=op.f("ck_original_files_sha256_length")
        ),
        sa.CheckConstraint(
            "length(storage_key) >= 1", name=op.f("ck_original_files_storage_key_nonempty")
        ),
        sa.CheckConstraint(
            "size_bytes BETWEEN 1 AND 26214400", name=op.f("ck_original_files_size_bounds")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_original_files_positive_version")),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["learning_resources.id"],
            name=op.f("fk_original_files_resource_id_learning_resources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_original_files")),
        sa.UniqueConstraint("resource_id", name=op.f("uq_original_files_resource_id")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_original_files_storage_key")),
        info={"owner": "resources"},
    )
    op.create_table(
        "resource_tags",
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.Column("association_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "association_version = 1", name=op.f("ck_resource_tags_immutable_association_version")
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["learning_resources.id"],
            name=op.f("fk_resource_tags_resource_id_learning_resources"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tags.id"], name=op.f("fk_resource_tags_tag_id_tags"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("resource_id", "tag_id", name=op.f("pk_resource_tags")),
        info={"owner": "taxonomy"},
    )
    op.create_index(op.f("ix_resource_tags_tag_id"), "resource_tags", ["tag_id"], unique=False)
    op.create_table(
        "review_records",
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("planned_date", sa.Date(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=False),
        sa.Column("result", sa.String(length=12), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("next_review_date", sa.Date(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "result <> 'NEEDS_REVIEW' OR next_review_date IS NOT NULL",
            name=op.f("ck_review_records_next_review_required"),
        ),
        sa.CheckConstraint(
            "result IN ('UNDERSTOOD', 'NEEDS_REVIEW')", name=op.f("ck_review_records_result")
        ),
        sa.CheckConstraint(
            "length(notes) BETWEEN 0 AND 5000", name=op.f("ck_review_records_notes_length")
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["learning_resources.id"],
            name=op.f("fk_review_records_resource_id_learning_resources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_records")),
        info={"owner": "reviews"},
    )
    op.create_index(
        "ix_review_records_resource_completed",
        "review_records",
        ["resource_id", "completed_at", "id"],
        unique=False,
    )
    op.create_table(
        "study_records",
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=False),
        sa.Column("progress_before", sa.Integer(), nullable=False),
        sa.Column("progress_after", sa.Integer(), nullable=False),
        sa.Column("status_before", sa.String(length=11), nullable=False),
        sa.Column("status_after", sa.String(length=11), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("questions_next", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "status_after IN ('UNREAD', 'IN_PROGRESS', 'COMPLETED', 'REVIEW_DUE', 'ARCHIVED')",
            name=op.f("ck_study_records_status_after"),
        ),
        sa.CheckConstraint(
            "status_before IN ('UNREAD', 'IN_PROGRESS', 'COMPLETED', 'REVIEW_DUE', 'ARCHIVED')",
            name=op.f("ck_study_records_status_before"),
        ),
        sa.CheckConstraint(
            "duration_seconds BETWEEN 0 AND 86400", name=op.f("ck_study_records_duration_bounds")
        ),
        sa.CheckConstraint(
            "length(questions_next) BETWEEN 0 AND 5000",
            name=op.f("ck_study_records_questions_next_length"),
        ),
        sa.CheckConstraint(
            "length(summary) BETWEEN 0 AND 5000", name=op.f("ck_study_records_summary_length")
        ),
        sa.CheckConstraint(
            "progress_after BETWEEN 0 AND 100", name=op.f("ck_study_records_progress_after_bounds")
        ),
        sa.CheckConstraint(
            "progress_before BETWEEN 0 AND 100",
            name=op.f("ck_study_records_progress_before_bounds"),
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["learning_resources.id"],
            name=op.f("fk_study_records_resource_id_learning_resources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_study_records")),
        info={"owner": "learning"},
    )
    op.create_index(
        "ix_study_records_resource_started",
        "study_records",
        ["resource_id", "started_at", "id"],
        unique=False,
    )


def downgrade() -> None:
    """Only empty development databases can be downgraded by this revision."""
    if context.is_offline_mode():
        raise RuntimeError("Initial downgrade requires an online empty-database check")
    connection = op.get_bind()
    for name in TABLES:
        has_data = connection.execute(
            sa.select(sa.literal(1)).select_from(sa.table(name)).limit(1)
        ).first()
        if has_data is not None:
            raise RuntimeError("Refusing to drop non-empty StudyPilot tables; back up data first")
    for name in reversed(TABLES):
        op.drop_table(name)
